# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d71e69947f3e0108ecbf3a79e714a019fa10d1c49793875e8c35a0dd678e1590122ef745614b65f00210c2aa3129043a29982270f4ae42723093a8ec230e022a

test:
  secret_key_base: 222609c80be74c8fc30f11895ab98b91a18693b46ffdab7524855e981b0092f5a5981e9622bcfa9554fe737158bba6e544bb618582cfb68d8ff309dab90b1bcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
